spring:
    docker:
        compose:
            lifecycle-management: start_only
    datasource:
        username: postgres
        password: aboba
        url: jdbc:postgresql://db:5432/test
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        root: error
        com.leute.spring_leute: info
        org:
            springframework:
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG